### ISSUE TITLE
Implement /programs, /studies, /trials

### ISSUE THREAD

**Issue by dlebauer** [terraref/brapi#14]
- breeding program
  - one or more trials 
    - one or more studies per trial, each study corresponds to a single location  

* **Program** A Program can contain multiple Trials. A Trial can contain multiple Studies.
* **Trial** Corresponds to the "investigation" concept in MIAPPE (Minimal Information about a Plant Phenotyping Experiment).
* **Study** a phenotyping experiment conducted at a **single geographic location**. One Trial can have multiple studies conducted (e.g. multi location international trials).

What breeding programs do we have?

1. Sorghum Biomass Association Panel
2. Durum Wheat
3. Sorghum recombinant inbred lines

**Comment by robkooper** [comment]
@dlebauer how do these map to BETY?

**Comment by dlebauer** [comment]
Studies that map to the MIAPPE concept of the same name

```sql
create temporary table studies (
select 
  id as studyDbId,
  name as studyName,
  description as studyDescription,
  start_date as startDate,
  end_date as endDate
  design as statisticalDesign.description
  (today < end_date) as active #TRUE/FALSE
 from experiments);
```

Not sure how to join to locations schemas sitegroups_sites join sites join experiments_sites],

**Comment by dlebauer** [comment]
* generated inserts to link experiments with trials in contrib/studies.Rmd
* inserts as sql are here: https://gist.github.com/dlebauer/f96c5250b90d2f2d09ce03ccd3dea7ab 
* the following has been applied to bety6

```sql
wget https://gist.githubusercontent.com/dlebauer/f96c5250b90d2f2d09ce03ccd3dea7ab/raw/4db4f8515c7eaeab7f3c288a0bbcdbd521db15e9/studies_inserts.sql
psql -U bety < studies_inserts.sql    
```

**Comment by robkooper** [comment]
studies is implemented, including germplasm and locations

**Comment by max-zilla** [comment]
implemented trials here: https://github.com/terraref/brapi/pull/33

**Comment by dlebauer** [comment]
these have all been implemented
