### ISSUE TITLE
Ensure that all implemented endpoints are compliant 

### ISSUE THREAD

**Issue by dlebauer** [terraref/brapi#17]
1. test against http://webapps.ipk-gatersleben.de/brapivalidator/
2. set up continuous integration to 
   * ensure that endpoints are complaint
   * require PRs to pass compliance (and other!) tests

**Comment by dlebauer** [comment]
From @BrapiCoordinatorSelby

> Yes, the BRAVA ui controls the backend via APIs, but those APIs are not documented. take a look at SingleTestResource.java https://github.com/plantbreeding/IPK-BrAPI-Validator

**Comment by robkooper** [comment]
Created a container that is part of the docker-compose. You can use it with either the docker container if you use `http://brapi:5000/brapi/v1` or you can use it when you run it in the editor/local machine by using `http://host.docker.internal:5000/brapi/v1` as the URL.

**Comment by BrapiCoordinatorSelby** [comment]
FYI, the IPK guys put an image of BRAVA up on DockerHub, if that makes your CI process easier.
https://hub.docker.com/r/ipkbit/brapi-validator
@robkooper I'm not sure if this was built using your docker file pull request, or one they made themselves.

**Comment by robkooper** [comment]
That might be very likely: https://github.com/plantbreeding/IPK-BrAPI-Validator/pull/37 got merged today.
