### ISSUE TITLE
regenerate stubs for v1.3, remove unused code

### ISSUE THREAD

**Issue by dlebauer** [terraref/brapi#18]
- [ ] reduce the openapi.yml to only provide the endpoints that we support
- [x] regenerate stubs
- [x] update README.md
   * document how to add new endpoints from the yml
- [x] get the API working again

**Comment by robkooper** [comment]
removed code to generate stubs, now is automagically.

**Comment by robkooper** [comment]
will close issue for now, we can cut down the brapi.yaml at a later time.
