### ISSUE TITLE
Return quality flag with all phenotypes

### ISSUE THREAD

**Issue by dlebauer** [terraref/brapi#26]
The traits table has a quality flag. 

* any data marked -1 should not be returned
* data marked "0" should indicate that it has not been checked, perhaps `"quality":"unchecked"`
* data marked "1" should indicate that it has been reviewed and approved perhaps `"quality":"unchecked"`

The values should follow a standard vocabulary ... perhaps [ISO 8000](https://en.wikipedia.org/wiki/ISO_8000) has some clues?

**Comment by tcnichol** [comment]
I could assign this to myself. I am not sure if we have traits implemented.

**Comment by dlebauer** [comment]
I think that records in the traits table translate to the 'observations' endpoint ... is that correct?

**Comment by max-zilla** [comment]
this has been implemented for the /observationunits endpoint - "quality": "checked" for 1, ""unchecked" for 0, -1s are omitted.

In testing phase on dev now.

**Comment by max-zilla** [comment]
implemented here: https://github.com/terraref/brapi/pull/33
