### ISSUE TITLE
Additions to observation unit

### ISSUE THREAD

**Issue by dlebauer** [terraref/brapi#27]

**Comment by dlebauer** [comment]
need to review and flush out observation unit endpoint 

Also 
— replicate # —> entity_id (in some cases)
— operator = traitsview.author (person who collected data)

**Comment by tcnichol** [comment]
Should I assign this to myself? I implemented the endpoint and this should not be too difficult.

**Comment by dlebauer** [comment]
yes, please do!

**Comment by tcnichol** [comment]
https://github.com/terraref/brapi/tree/issue-27/addition-observation-unit

branch for this issue

**Comment by max-zilla** [comment]
this has been implemented. replicate will be null if unavailable. sample record:

```
{
observationUnitName: "MAC Field Scanner Season 4 Range 1 Column 1",
observations: [
{
observationDbId: "6002240848",
observationTimeStamp: "2017-07-25T19:00:00Z",
observationVariableDbId: "6000000012",
observationVariableName: "canopy_cover",
season: "MAC Sorghum Season 4",
value: "0"
}
],
observationtreatment: "Pre-plant Nitrogen fertilizer incorporated in the field",
operator: "Zongyang, Li",
replicate: null,
studyDbId: "6000000010",
treatmentDbId: 6000000020
}
```

**Comment by max-zilla** [comment]
implemented here: https://github.com/terraref/brapi/pull/33
