### ISSUE TITLE
Add query parameters to observationunits endpoint

### ISSUE THREAD

**Issue by KristinaRiemer** [terraref/brapi#38]
It looks like, although the observationunits endpoint itself no longer returns observation values, the observationUnitDbId query parameter (e.g., https://brapi.workbench.terraref.org/brapi/v1/observationunits?observationUnitDbId=MAC Field Scanner Season 4 Range 48 Column 11 E) does return them. 

I'm hoping it's possible to get the studyDbId (e.g., https://brapi.workbench.terraref.org/brapi/v1/observationunits?studyDbId=6000000034) and observationVariableDbId (https://brapi.workbench.terraref.org/brapi/v1/observationunits?observationVariableDbId=stand_count) query parameters to be able to return observation values also? This is because we're looking to get values for only certain variables and for particular studies. 

I don't have much experience with APIs and their development, but it seems like maybe a query that's similar to the one set up for observationUnitDbId (lines 45-81 of [observationunits script](https://github.com/terraref/brapi/blob/master/api/observationunits.py)) could be done for those other two parameters?

**Comment by dlebauer** [comment]
I think that you need to use the integer ID values for ObservationVariableDbId i.e. 
`&observationVariableDbId=6000000196`

**Comment by dlebauer** [comment]
studydbid should be here: https://github.com/terraref/brapi/blob/master/api/observationunits.py#L91
